name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PEM_KEY }}" > ~/prueba2.pem
          mv ~/prueba2.pem ~/.ssh/prueba2.pem
          chmod 400 ~/.ssh/prueba2.pem

      - name: Connect to EC2 and deploy
        env:
          EC2_HOST: ec2-18-212-195-45.compute-1.amazonaws.com
          EC2_USER: ubuntu
          DOCKER_IMAGE: mferpena/typescript-backend:latest
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prueba2.pem "${{ env.EC2_USER }}@${{ env.EC2_HOST }}" << 'EOF'
            # Pull the Docker image from Docker Hub
            sudo docker pull ${{ env.DOCKER_IMAGE }}

            # Stop and remove the old container if it exists
            CONTAINER_ID=$(sudo docker ps -q -f name=typescript-backend)
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            # Run the new container
            sudo docker run -d --name typescript-backend -p 5000:5000 ${{ env.DOCKER_IMAGE }}
          EOF
