name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker stop typescript-backend || true
          docker rm typescript-backend || true
          docker pull mferpena/typescript-backend:latest
          docker run -d --name typescript-backend -p 5000:5000 mferpena/typescript-backend:latest
