name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ~/prueba2.pem
          # Agregar una nueva línea al final del archivo PEM
          echo "" >> ~/prueba2.pem
          chmod 400 ~/prueba2.pem
          ls -l ~/prueba2.pem
          cat ~/prueba2.pem

      - name: Connect to EC2 and deploy
        env:
          EC2_HOST: ec2-18-212-195-45.compute-1.amazonaws.com
          EC2_USER: ubuntu
          DOCKER_IMAGE: mferpena/typescript-backend:latest
        run: |
          ssh -i ~/prueba2.pem ubuntu@ec2-44-202-13-34.compute-1.amazonaws.com "docker stop typescript-backend && docker rm typescript-backend && docker pull ${{ env.DOCKER_IMAGE }} && docker run -d --name typescript-backend -p 5000:5000 ${{ env.DOCKER_IMAGE }}"
